import React, { useEffect, useRef, useState } from 'react'
import {
  ActivityIndicator,
  Alert,
  Animated,
  BackHandler,
  KeyboardAvoidingView,
  Modal,
  Platform,
  Pressable,
  ScrollView,
  Text,
  TextInput,
  View,
  useWindowDimensions,
} from 'react-native'
import * as Contacts from 'expo-contacts'
import { useFonts } from 'expo-font'
import {
  Manrope_400Regular,
  Manrope_500Medium,
  Manrope_600SemiBold,
  Manrope_700Bold,
  Manrope_800ExtraBold,
} from '@expo-google-fonts/manrope'

import { AppShell, CenteredMessage, PageContent, ScrollablePage } from './src/components/AppShell'
import {
  BillsHomeTab,
  CustomersHomeTab,
  FloatingPrimaryAction,
  LedgerBottomNav,
  SettingsHomeTab,
  bottomNavWrapStyle,
} from './src/components/LauncherHome'
import CustomerSheet from './src/components/CustomerSheet'
import InvoiceEditor from './src/components/InvoiceEditor'
import InvoicePreview from './src/components/InvoicePreview'
import ScreenHeader from './src/components/ScreenHeader'
import { ActionButton, FieldGrid, LabeledInput, PanelHeader, THEME, compactPanelStyle, panelStyle } from './src/components/InvoiceComponents'
import { GestureHandlerRootView } from 'react-native-gesture-handler'
import { useSafeAreaInsets } from 'react-native-safe-area-context'
import { extractBusinessContactFields, extractCustomerFromContact } from './src/contactUtils'
import {
  createBill,
  createBusinessProfile,
  createCustomer,
  createItem,
  getDefaultState,
  mapCustomerToInvoiceFields,
} from './src/constants'
import {
  deleteBill,
  deleteCustomer,
  exportDatabaseBackup,
  getBusinessProfile,
  getThemeMode,
  initializeDatabase,
  listBills,
  listCustomers,
  replaceDatabaseWithBackup,
  saveBusinessProfile,
  saveBill,
  saveCustomer,
  saveThemeMode,
  summarizeBackupDocument,
} from './src/database'
import { downloadPdf, shareCombinedPdf, sharePdf } from './src/pdf'
import {
  getMinimumDueDate,
  calculateSummary,
  getGstLabels,
  getNextInvoiceNumber,
  hasPreviewableInvoiceItems,
  isDueDateAfterInvoiceDate,
  isAutoGeneratedInvoiceNumber,
  normalizeNumber,
} from './src/utils'
import {
  downloadBackupFromSupabase,
  getSupabaseBackupConnection,
  isSupabaseBackupConfigured,
  signInSupabaseBackupAccount,
  signOutSupabaseBackupAccount,
  signUpSupabaseBackupAccount,
  uploadBackupToSupabase,
} from './src/supabaseBackup'

const HOME_TAB_KEYS = ['bills', 'customers', 'settings']

if (!globalThis.__riceTraderTypographyDefaultsApplied) {
  Text.defaultProps = Text.defaultProps || {}
  TextInput.defaultProps = TextInput.defaultProps || {}
  Text.defaultProps.style = [{ fontFamily: 'Manrope_500Medium' }, Text.defaultProps.style].filter(Boolean)
  TextInput.defaultProps.style = [{ fontFamily: 'Manrope_500Medium' }, TextInput.defaultProps.style].filter(Boolean)
  globalThis.__riceTraderTypographyDefaultsApplied = true
}

export default function App() {
  const insets = useSafeAreaInsets()
  const [fontsLoaded] = useFonts({
    Manrope_400Regular,
    Manrope_500Medium,
    Manrope_600SemiBold,
    Manrope_700Bold,
    Manrope_800ExtraBold,
  })
  const emptyInvoiceCustomerFields = {
    customerId: null,
    customerName: '',
    customerAddress: '',
    customerGstin: '',
    customerPhone: '',
    customerEmail: '',
    placeOfSupply: '',
  }
  const [customers, setCustomers] = useState([])
  const [bills, setBills] = useState([])
  const [invoice, setInvoice] = useState(null)
  const [customerDraft, setCustomerDraft] = useState(null)
  const [businessProfile, setBusinessProfile] = useState(() => createBusinessProfile())
  const [screen, setScreen] = useState('launcher')
  const [homeTab, setHomeTab] = useState('bills')
  const [busyAction, setBusyAction] = useState(null)
  const [isReady, setIsReady] = useState(false)
  const [loadError, setLoadError] = useState('')
  const [isCustomerSheetOpen, setIsCustomerSheetOpen] = useState(false)
  const [customerSheetMode, setCustomerSheetMode] = useState('view')
  const [themeMode, setThemeMode] = useState('light')
  const [dataTransferAction, setDataTransferAction] = useState(null)
  const [backupConnection, setBackupConnection] = useState({
    configured: isSupabaseBackupConfigured(),
    connected: false,
    email: '',
    userId: '',
  })
  const [isBackupAccountSheetOpen, setIsBackupAccountSheetOpen] = useState(false)
  const [backupAccountMode, setBackupAccountMode] = useState('signIn')
  const [backupAccountEmail, setBackupAccountEmail] = useState('')
  const [backupAccountPassword, setBackupAccountPassword] = useState('')
  const [isBackupAccountSubmitting, setIsBackupAccountSubmitting] = useState(false)
  const [pendingBackupAction, setPendingBackupAction] = useState(null)
  const [blockingLoader, setBlockingLoader] = useState(null)
  const backupConnectionRef = useRef(backupConnection)
  const dataTransferActionRef = useRef(dataTransferAction)
  const autoBackupTimerRef = useRef(null)
  const autoBackupRunningRef = useRef(false)
  const autoBackupRetryRequestedRef = useRef(false)
  const autoBackupFailureAlertedRef = useRef(false)
  const launcherPagerRef = useRef(null)
  const launcherPagerIndexRef = useRef(HOME_TAB_KEYS.indexOf('bills'))
  const { width } = useWindowDimensions()
  const bottomNavOffset = useRef(new Animated.Value(0)).current
  const bottomNavOpacity = useRef(new Animated.Value(1)).current
  const bottomNavVisible = useRef(true)
  const lastLauncherScrollY = useRef(0)
  const [isBottomNavInteractive, setIsBottomNavInteractive] = useState(true)
  const bottomNavAnimationUsesNativeDriver = Platform.OS !== 'android'

  const isCompact = width < 560
  const isTablet = width >= 720
  const isWide = width >= 960
  const showCompactPreview = width < 860
  const launcherIsLight = themeMode === 'light'
  const showFloatingPrimaryAction = screen === 'launcher' && (homeTab === 'bills' || homeTab === 'customers')
  const isExistingBill = invoice ? bills.some((bill) => bill.id === invoice.id) : false
  const activeInvoice = {
    ...(invoice || getDefaultState()),
    ...businessProfile,
  }
  const summary = calculateSummary(activeInvoice.items)
  const { cgstLabel, sgstLabel } = getGstLabels(activeInvoice.items)

  useEffect(() => {
    bootstrap()
  }, [])

  useEffect(() => {
    if (screen !== 'launcher') {
      revealBottomNav()
    }
  }, [screen])

  useEffect(() => {
    backupConnectionRef.current = backupConnection
  }, [backupConnection])

  useEffect(() => {
    dataTransferActionRef.current = dataTransferAction
  }, [dataTransferAction])

  useEffect(() => {
    if (Platform.OS !== 'android') {
      return undefined
    }

    const backSubscription = BackHandler.addEventListener('hardwareBackPress', () => {
      if (isBackupAccountSheetOpen) {
        closeBackupAccountSheet()
        return true
      }

      if (isCustomerSheetOpen) {
        closeCustomerSheet()
        return true
      }

      if (screen === 'preview') {
        setScreen('edit')
        return true
      }

      if (screen === 'edit') {
        openLauncher('bills')
        return true
      }

      if (homeTab !== 'bills') {
        openLauncher('bills')
        return true
      }

      return false
    })

    return () => {
      backSubscription.remove()
    }
  }, [homeTab, isBackupAccountSheetOpen, isCustomerSheetOpen, screen, isBackupAccountSubmitting])

  useEffect(() => {
    return () => {
      if (autoBackupTimerRef.current) {
        clearTimeout(autoBackupTimerRef.current)
      }
    }
  }, [])

  useEffect(() => {
    if (screen !== 'launcher' || !launcherPagerRef.current) {
      return
    }

    const targetIndex = Math.max(0, HOME_TAB_KEYS.indexOf(homeTab))
    launcherPagerIndexRef.current = targetIndex
    launcherPagerRef.current.scrollTo({
      x: targetIndex * width,
      animated: isReady,
    })
  }, [homeTab, isReady, screen, width])

  if (!fontsLoaded) {
    return null
  }

  function confirmAction({ title, message, confirmLabel, destructive = false, onConfirm }) {
    Alert.alert(title, message, [
      { text: 'Cancel', style: 'cancel' },
      {
        text: confirmLabel,
        style: destructive ? 'destructive' : 'default',
        onPress: () => {
          void onConfirm?.()
        },
      },
    ])
  }

  function hasCustomerDetails(customer) {
    return [
      customer?.name,
      customer?.address,
      customer?.gstin,
      customer?.phone,
      customer?.email,
      customer?.placeOfSupply,
      customer?.notes,
    ].some((value) => Boolean(String(value || '').trim()))
  }

  function createDraftBill(customer = null, overrides = {}, sourceBills = bills) {
    const nextBill = createBill({
      customerId: customer?.id || null,
      ...mapCustomerToInvoiceFields(customer),
      items: [],
      ...overrides,
    })

    return {
      ...nextBill,
      invoiceNumber: getNextInvoiceNumber(sourceBills, nextBill.invoiceDate, nextBill.id),
    }
  }

  async function bootstrap() {
    let startupRestoreError = null

    try {
      await initializeDatabase()

      try {
        const connection = await refreshBackupConnection()

        if (connection.connected) {
          try {
            setBlockingLoader({
              title: 'Loading cloud backup',
              body: 'Downloading the latest Supabase backup for this device.',
            })
            const latestBackup = await downloadBackupFromSupabase()
            setBlockingLoader({
              title: 'Restoring cloud backup',
              body: 'Applying the downloaded backup to your local billing data.',
            })
            await replaceDatabaseWithBackup(latestBackup.contents)
          } catch (error) {
            const errorMessage = String(error?.message || '').toLowerCase()

            if (!errorMessage.includes('no supabase backup was found')) {
              startupRestoreError = error
            }
          }
        }
      } catch (_error) {
        setBackupConnection({
          configured: isSupabaseBackupConfigured(),
          connected: false,
          email: '',
          userId: '',
        })
      }

      await refreshRecords()
      setLoadError('')
      setIsReady(true)
      setBlockingLoader(null)

      if (startupRestoreError) {
        Alert.alert(
          'Cloud restore unavailable',
          startupRestoreError.message || 'The latest Supabase backup could not be restored on app open. Local data is still available on this device.'
        )
      }
    } catch (error) {
      setLoadError(error.message || 'Unable to open the local billing database.')
      setIsReady(true)
      setBlockingLoader(null)
    }
  }

  async function refreshRecords(options = {}) {
    const [nextCustomers, nextBills, nextBusinessProfile, nextThemeMode] = await Promise.all([
      listCustomers(),
      listBills(),
      getBusinessProfile(),
      getThemeMode(),
    ])

    setCustomers(nextCustomers)
    setBills(nextBills)
    setBusinessProfile(nextBusinessProfile)
    setThemeMode(nextThemeMode)

    const nextInvoice =
      nextBills.find((bill) => bill.id === options.billId) ||
      nextBills.find((bill) => bill.id === invoice?.id) ||
      nextBills[0] ||
      createDraftBill(null, {}, nextBills)
    const nextCustomer =
      nextCustomers.find((customer) => customer.id === options.customerId) ||
      nextCustomers.find((customer) => customer.id === customerDraft?.id) ||
      nextCustomers[0] ||
      createCustomer()

    setInvoice(nextInvoice)
    setCustomerDraft(nextCustomer)
  }

  function updateField(field, value) {
    setInvoice((current) => {
      const baseInvoice = current || createDraftBill()
      const nextInvoice = {
        ...baseInvoice,
        [field]: value,
      }

      const isSavedBill = bills.some((bill) => bill.id === baseInvoice.id)
      if (field === 'invoiceDate' && !isSavedBill && isAutoGeneratedInvoiceNumber(baseInvoice.invoiceNumber)) {
        nextInvoice.invoiceNumber = getNextInvoiceNumber(bills, value, baseInvoice.id)
      }

      if (field === 'invoiceDate' && nextInvoice.dueDate && !isDueDateAfterInvoiceDate(value, nextInvoice.dueDate)) {
        nextInvoice.dueDate = getMinimumDueDate(value)
      }

      if (field === 'dueDate' && value && !isDueDateAfterInvoiceDate(nextInvoice.invoiceDate, value)) {
        nextInvoice.dueDate = getMinimumDueDate(nextInvoice.invoiceDate)
      }

      return nextInvoice
    })
  }

  function updateItem(itemId, field, value) {
    setInvoice((current) => ({
      ...(current || createDraftBill()),
      items: (current?.items || []).map((item) => (item.id === itemId ? { ...item, [field]: value } : item)),
    }))
  }

  function addItem() {
    const currentItems = invoice?.items || []
    const lastItem = currentItems[currentItems.length - 1]

    if (lastItem) {
      const missingFields = []

      if (!String(lastItem.description || '').trim()) {
        missingFields.push('description')
      }

      if (!String(lastItem.bagType || '').trim()) {
        missingFields.push('bag type')
      }

      if (normalizeNumber(lastItem.quantity) <= 0) {
        missingFields.push('quantity')
      }

      if (normalizeNumber(lastItem.rate) <= 0) {
        missingFields.push('rate')
      }

      if (missingFields.length > 0) {
        const missingLabel =
          missingFields.length === 1
            ? missingFields[0]
            : `${missingFields.slice(0, -1).join(', ')} and ${missingFields[missingFields.length - 1]}`

        Alert.alert(
          'Complete the current line item',
          `Fill the previous item's ${missingLabel} before adding a new line item.`
        )
        return
      }
    }

    setInvoice((current) => ({
      ...(current || createDraftBill()),
      items: [...(current?.items || []), createItem()],
    }))
  }

  function removeItem(itemId) {
    setInvoice((current) => {
      const nextItems = (current?.items || []).filter((item) => item.id !== itemId)

      return {
        ...(current || createDraftBill()),
        items: nextItems,
      }
    })
  }

  function updateCustomerDraftField(field, value) {
    setCustomerDraft((current) => ({
      ...(current || createCustomer()),
      [field]: value,
    }))
  }

  function confirmRemoveItem(itemId) {
    const item = (invoice?.items || []).find((entry) => entry.id === itemId)
    const itemLabel = String(item?.description || item?.bagType || 'this line item').trim()

    confirmAction({
      title: 'Remove item',
      message: `Remove ${itemLabel} from this invoice draft?`,
      confirmLabel: 'Remove',
      destructive: true,
      onConfirm: () => removeItem(itemId),
    })
  }

  function openLauncher(tab) {
    if (tab) {
      setHomeTab(tab)
    }
    revealBottomNav()
    setIsCustomerSheetOpen(false)
    setScreen('launcher')
  }

  function openBillEditor(bill) {
    revealBottomNav()
    setInvoice(bill)
    setScreen('edit')
    setHomeTab('bills')
  }

  function openCustomerEditor(customer) {
    revealBottomNav()
    setCustomerDraft(customer)
    setHomeTab('customers')
    setScreen('launcher')
    setCustomerSheetMode('view')
    setIsCustomerSheetOpen(true)
  }

  async function createNewBill(customer = null) {
    try {
      revealBottomNav()
      const nextBill = createDraftBill(customer)
      setInvoice(nextBill)
      setScreen('edit')
      setHomeTab('bills')
    } catch (error) {
      Alert.alert('Unable to create bill', error.message || 'Please try again.')
    }
  }

  async function persistBusinessProfileDraft(nextProfile, showSavedAlert, options = {}) {
    const { shouldQueueBackup = true } = options

    try {
      const savedProfile = await saveBusinessProfile(nextProfile)
      setBusinessProfile(savedProfile)

      if (shouldQueueBackup) {
        scheduleAutomaticBackup()
      }

      if (showSavedAlert) {
        Alert.alert('Settings saved', 'Business and bank setup were stored for all bills on this device.')
      }

      return savedProfile
    } catch (error) {
      Alert.alert('Unable to save settings', error.message || 'Please try again.')
      throw error
    }
  }

  async function persistBusinessSettings(showSavedAlert, options = {}) {
    return persistBusinessProfileDraft(businessProfile, showSavedAlert, options)
  }

  async function pickSystemContact() {
    if (Platform.OS === 'web') {
      Alert.alert('Contacts unavailable', 'Contact import is available on Android and iPhone builds.')
      return null
    }

    try {
      const permission = await Contacts.requestPermissionsAsync()

      if (permission.status !== 'granted') {
        Alert.alert('Contacts permission needed', 'Allow contacts access to import a saved contact into the app.')
        return null
      }

      const selectedContact = await Contacts.presentContactPickerAsync()

      if (!selectedContact?.id) {
        return null
      }

      return (
        (await Contacts.getContactByIdAsync(selectedContact.id, [
          Contacts.Fields.Name,
          Contacts.Fields.FirstName,
          Contacts.Fields.LastName,
          Contacts.Fields.PhoneNumbers,
          Contacts.Fields.Emails,
          Contacts.Fields.Addresses,
        ])) || selectedContact
      )
    } catch (error) {
      Alert.alert('Unable to open contacts', error.message || 'Please try again.')
      return null
    }
  }

  async function importCustomerFromContacts() {
    const contact = await pickSystemContact()

    if (!contact) {
      return
    }

    const { phone } = extractCustomerFromContact(contact)

    if (!phone) {
      Alert.alert('No phone number found', 'The selected contact does not have a phone number to import.')
      return
    }

    setCustomerDraft((current) => ({
      ...(current || createCustomer()),
      phone,
    }))
  }

  async function pickBusinessContactFields() {
    const contact = await pickSystemContact()

    if (!contact) {
      return null
    }

    const nextFields = extractBusinessContactFields(contact)
    const { companyPhone, companyEmail } = nextFields

    if (!companyPhone && !companyEmail) {
      Alert.alert('No contact details found', 'The selected contact does not have a phone number or email to import.')
      return null
    }

    return Object.fromEntries(Object.entries(nextFields).filter(([, value]) => value))
  }

  function createNewCustomer() {
    revealBottomNav()
    setCustomerDraft(createCustomer())
    setHomeTab('customers')
    setScreen('launcher')
    setCustomerSheetMode('edit')
    setIsCustomerSheetOpen(true)
  }

  function hideBottomNav() {
    if (!bottomNavVisible.current) {
      return
    }

    bottomNavVisible.current = false
    setIsBottomNavInteractive(false)
    bottomNavOffset.stopAnimation()
    bottomNavOpacity.stopAnimation()
    Animated.parallel([
      Animated.timing(bottomNavOffset, {
        toValue: 120,
        duration: 220,
        useNativeDriver: bottomNavAnimationUsesNativeDriver,
      }),
      Animated.timing(bottomNavOpacity, {
        toValue: 0,
        duration: 180,
        useNativeDriver: bottomNavAnimationUsesNativeDriver,
      }),
    ]).start()
  }

  function revealBottomNav() {
    lastLauncherScrollY.current = 0

    if (bottomNavVisible.current) {
      setIsBottomNavInteractive(true)
      bottomNavOffset.stopAnimation()
      bottomNavOpacity.stopAnimation()
      bottomNavOffset.setValue(0)
      bottomNavOpacity.setValue(1)
      return
    }

    bottomNavVisible.current = true
    setIsBottomNavInteractive(true)
    bottomNavOffset.stopAnimation()
    bottomNavOpacity.stopAnimation()
    Animated.parallel([
      Animated.spring(bottomNavOffset, {
        toValue: 0,
        damping: 18,
        stiffness: 180,
        mass: 0.9,
        useNativeDriver: bottomNavAnimationUsesNativeDriver,
      }),
      Animated.timing(bottomNavOpacity, {
        toValue: 1,
        duration: 220,
        useNativeDriver: bottomNavAnimationUsesNativeDriver,
      }),
    ]).start()
  }

  function handleLauncherScroll(event) {
    const nextY = Math.max(0, event.nativeEvent.contentOffset.y)
    const delta = nextY - lastLauncherScrollY.current
    lastLauncherScrollY.current = nextY

    if (nextY <= 12) {
      revealBottomNav()
      return
    }

    if (delta > 8) {
      hideBottomNav()
      return
    }

    if (delta < -8) {
      revealBottomNav()
    }
  }

  function closeCustomerSheet() {
    setIsCustomerSheetOpen(false)
    setCustomerSheetMode('view')
  }

  function editCustomerInSheet() {
    setCustomerSheetMode('edit')
  }

  function handleCreateBillFromCustomerSheet(customer) {
    setIsCustomerSheetOpen(false)
    createNewBill(customer)
  }

  function handleHomeTabChange(tab) {
    revealBottomNav()
    setHomeTab(tab)
    setIsCustomerSheetOpen(false)
    setCustomerSheetMode('view')
  }

  function handleLauncherPagerMomentumEnd(event) {
    const nextIndex = Math.max(0, Math.min(HOME_TAB_KEYS.length - 1, Math.round(event.nativeEvent.contentOffset.x / width)))
    const nextTab = HOME_TAB_KEYS[nextIndex] || 'bills'
    launcherPagerIndexRef.current = nextIndex

    if (nextTab !== homeTab) {
      handleHomeTabChange(nextTab)
    }
  }

  async function toggleThemeMode() {
    const previousThemeMode = themeMode
    const nextThemeMode = previousThemeMode === 'light' ? 'dark' : 'light'

    setThemeMode(nextThemeMode)

    try {
      await saveThemeMode(nextThemeMode)
      scheduleAutomaticBackup()
    } catch (error) {
      setThemeMode(previousThemeMode)
      Alert.alert('Unable to save theme', error.message || 'Please try again.')
    }
  }

  function applyCustomerToInvoice(customer) {
    setInvoice((current) => ({
      ...(current || createDraftBill()),
      ...(customer ? mapCustomerToInvoiceFields(customer) : emptyInvoiceCustomerFields),
      customerId: customer?.id || null,
    }))
  }

  async function persistInvoice(showSavedAlert) {
    const currentInvoice = activeInvoice

    try {
      const selectedCustomer = customers.find((customer) => customer.id === currentInvoice.customerId) || null
      const customerSnapshot = selectedCustomer
        ? mapCustomerToInvoiceFields(selectedCustomer)
        : emptyInvoiceCustomerFields
      const normalizedDueDate =
        currentInvoice.dueDate && !isDueDateAfterInvoiceDate(currentInvoice.invoiceDate, currentInvoice.dueDate)
          ? getMinimumDueDate(currentInvoice.invoiceDate)
          : currentInvoice.dueDate

      const savedBill = await saveBill({
        ...currentInvoice,
        dueDate: normalizedDueDate,
        customerId: selectedCustomer?.id || null,
        ...customerSnapshot,
      })

      await refreshRecords({
        billId: savedBill.id,
        customerId: selectedCustomer?.id || customerDraft?.id,
      })
      setInvoice(savedBill)
      scheduleAutomaticBackup()

      if (showSavedAlert) {
        Alert.alert('Bill saved', 'The bill was stored on this device.')
      }

      return savedBill
    } catch (error) {
      Alert.alert('Unable to save bill', error.message || 'Please try again.')
      throw error
    }
  }

  async function persistCustomerDraft(showSavedAlert) {
    const currentCustomer = customerDraft || createCustomer()

    if (!hasCustomerDetails(currentCustomer)) {
      Alert.alert(
        'Customer details required',
        'Add at least one customer detail before saving this profile.'
      )
      return null
    }

    try {
      const savedCustomer = await saveCustomer(currentCustomer)
      await refreshRecords({ customerId: savedCustomer.id })
      setCustomerDraft(savedCustomer)
      scheduleAutomaticBackup()

      if (invoice?.customerId === savedCustomer.id) {
        setInvoice((current) => ({
          ...(current || createDraftBill()),
          ...mapCustomerToInvoiceFields(savedCustomer),
          customerId: savedCustomer.id,
        }))
      }

      if (showSavedAlert) {
        Alert.alert('Customer saved', 'The customer profile was stored on this device.')
      }

      setIsCustomerSheetOpen(false)
      setCustomerSheetMode('view')
      setScreen('launcher')
      setHomeTab('customers')
      return savedCustomer
    } catch (error) {
      Alert.alert('Unable to save customer', error.message || 'Please try again.')
      throw error
    }
  }

  function confirmPersistCustomerDraft() {
    const currentCustomer = customerDraft || createCustomer()
    const isExistingCustomer = customers.some((customer) => customer.id === currentCustomer.id)
    const customerName = String(currentCustomer.name || 'this customer').trim()

    if (!hasCustomerDetails(currentCustomer)) {
      Alert.alert(
        'Customer details required',
        'Add at least one customer detail before creating a customer.'
      )
      return
    }

    confirmAction({
      title: isExistingCustomer ? 'Save customer changes' : 'Create customer',
      message: isExistingCustomer
        ? `Save the latest changes for ${customerName}?`
        : `Create ${customerName} in your local customer records?`,
      confirmLabel: isExistingCustomer ? 'Save' : 'Create',
      onConfirm: () => persistCustomerDraft(true),
    })
  }

  async function handleOpenPreview() {
    if (!hasPreviewableInvoiceItems(invoice?.items)) {
      Alert.alert(
        'Complete one item first',
        'Preview is available after at least one line item has a description, bag type, quantity, and rate.'
      )
      return
    }

    await persistBusinessSettings(false, { shouldQueueBackup: false })
    setScreen('preview')
  }

  async function handleDownloadPdf() {
    setBusyAction('download')

    try {
      await persistBusinessSettings(false, { shouldQueueBackup: false })
      const savedBill = await persistInvoice(false)
      await downloadPdf(savedBill)
      openLauncher('bills')
      Alert.alert('PDF ready', 'The invoice PDF was generated. Use the share sheet to save or send it.')
    } catch (error) {
      Alert.alert('Unable to generate PDF', error.message || 'Please try again.')
    } finally {
      setBusyAction(null)
    }
  }

  async function handleSharePdf() {
    setBusyAction('share')

    try {
      await persistBusinessSettings(false, { shouldQueueBackup: false })
      const savedBill = await persistInvoice(false)
      await sharePdf(savedBill)
      openLauncher('bills')
    } catch (error) {
      Alert.alert('Unable to share PDF', error.message || 'Please try again.')
    } finally {
      setBusyAction(null)
    }
  }

  async function handleSaveFromPreview() {
    setBusyAction('save')

    try {
      await persistBusinessSettings(false, { shouldQueueBackup: false })
      await persistInvoice(true)
      openLauncher('bills')
    } catch (error) {
      Alert.alert('Unable to save bill', error.message || 'Please try again.')
    } finally {
      setBusyAction(null)
    }
  }

  function confirmSaveInvoiceFromPreview() {
    const invoiceLabel = String(activeInvoice.invoiceNumber || 'this invoice').trim()

    confirmAction({
      title: 'Save invoice',
      message: `Save ${invoiceLabel} to your local billing records?`,
      confirmLabel: 'Save',
      onConfirm: () => handleSaveFromPreview(),
    })
  }

  async function handleShareBillFromList(bill) {
    setBusyAction('share')

    try {
      await persistBusinessSettings(false)
      await sharePdf({
        ...bill,
        ...businessProfile,
      })
    } catch (error) {
      Alert.alert('Unable to share PDF', error.message || 'Please try again.')
    } finally {
      setBusyAction(null)
    }
  }

  async function handleShareBillsFromList(selectedBills) {
    if (!selectedBills?.length) {
      return false
    }

    setBusyAction('share')

    try {
      await persistBusinessSettings(false)
      await shareCombinedPdf(
        selectedBills.map((bill) => ({
          ...bill,
          ...businessProfile,
        }))
      )
      return true
    } catch (error) {
      Alert.alert('Unable to share PDFs', error.message || 'Please try again.')
      return false
    } finally {
      setBusyAction(null)
    }
  }

  async function handleExportBackup() {
    if (!(await ensureBackupConnection('export'))) {
      return
    }

    setDataTransferAction('export')

    try {
      await persistBusinessSettings(false, { shouldQueueBackup: false })
      const backup = await exportDatabaseBackup()
      const uploadResult = await uploadBackupToSupabase(backup)
      await refreshBackupConnection()

      Alert.alert(
        'Backup uploaded',
        `${uploadResult.fileName || 'The backup snapshot'} was uploaded with ${backup.summary.customers} customers, ${backup.summary.bills} bills, and ${backup.summary.settings} settings${uploadResult.email ? ` for ${uploadResult.email}` : ''}. Use the same backup account on another device to restore it.`
      )
    } catch (error) {
      Alert.alert('Unable to export backup', error.message || 'Please try again.')
    } finally {
      setDataTransferAction(null)
    }
  }

  async function performRestoreBackup(backupDocument, fileName) {
    setDataTransferAction('restore')
    setBlockingLoader({
      title: 'Restoring backup',
      body: 'Replacing the local database on this device with the downloaded Supabase backup.',
    })

    try {
      const restoreSummary = await replaceDatabaseWithBackup(backupDocument)
      await refreshRecords()
      openLauncher('settings')

      Alert.alert(
        'Backup restored',
        `${fileName} replaced the local data on this device with ${restoreSummary.customers} customers, ${restoreSummary.bills} bills, and ${restoreSummary.settings} settings.`
      )
    } catch (error) {
      Alert.alert('Unable to restore backup', error.message || 'Please try again.')
    } finally {
      setDataTransferAction(null)
      setBlockingLoader(null)
    }
  }

  async function handleRestoreBackup() {
    if (!(await ensureBackupConnection('restore'))) {
      return
    }

    setDataTransferAction('restore')
    setBlockingLoader({
      title: 'Loading cloud backup',
      body: 'Downloading the latest Supabase backup so you can confirm the restore.',
    })

    try {
      const selectedBackup = await downloadBackupFromSupabase()
      const backupLabel = selectedBackup.fileName || backupConnection.email || 'your Supabase backup'
      const backupSummary = summarizeBackupDocument(selectedBackup.contents)

      Alert.alert(
        'Restore backup',
        `Replace the local data on this device with the cloud backup from ${backupLabel}?\n\nIncoming backup:\nCustomers: ${backupSummary.customers}\nBills: ${backupSummary.bills}\nSettings: ${backupSummary.settings}\n\nThis will overwrite the current local data on this device.`,
        [
          { text: 'Cancel', style: 'cancel' },
          {
            text: 'Restore now',
            onPress: () => {
              void performRestoreBackup(selectedBackup.contents, backupLabel)
            },
          },
        ]
      )
    } catch (error) {
      Alert.alert('Unable to read backup', error.message || 'Please try again.')
    } finally {
      setDataTransferAction(null)
      setBlockingLoader(null)
    }
  }

  async function refreshBackupConnection() {
    const connection = await getSupabaseBackupConnection()
    setBackupConnection(connection)
    return connection
  }

  function scheduleAutomaticBackup() {
    if (autoBackupTimerRef.current) {
      clearTimeout(autoBackupTimerRef.current)
    }

    autoBackupTimerRef.current = setTimeout(() => {
      autoBackupTimerRef.current = null
      void runAutomaticBackup()
    }, 1200)
  }

  async function runAutomaticBackup() {
    if (autoBackupRunningRef.current) {
      autoBackupRetryRequestedRef.current = true
      return
    }

    if (dataTransferActionRef.current) {
      autoBackupRetryRequestedRef.current = true
      scheduleAutomaticBackup()
      return
    }

    const connection = backupConnectionRef.current

    if (!connection?.configured || !connection?.connected) {
      return
    }

    autoBackupRunningRef.current = true
    autoBackupRetryRequestedRef.current = false

    try {
      const backup = await exportDatabaseBackup()
      await uploadBackupToSupabase(backup)
      autoBackupFailureAlertedRef.current = false
      await refreshBackupConnection()
    } catch (error) {
      if (!autoBackupFailureAlertedRef.current) {
        autoBackupFailureAlertedRef.current = true
        Alert.alert(
          'Automatic backup paused',
          error.message || 'The latest backup could not be uploaded to Supabase. Automatic backup will resume after reconnecting, and you can still use manual upload from Settings.'
        )
      }
    } finally {
      autoBackupRunningRef.current = false

      if (autoBackupRetryRequestedRef.current) {
        autoBackupRetryRequestedRef.current = false
        scheduleAutomaticBackup()
      }
    }
  }

  async function ensureBackupConnection(nextAction) {
    if (!isSupabaseBackupConfigured()) {
      Alert.alert(
        'Supabase backup not configured',
        'Add EXPO_PUBLIC_SUPABASE_URL and EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY to enable cloud backup and restore.'
      )
      return false
    }

    const connection = await refreshBackupConnection()

    if (connection.connected) {
      return true
    }

    setPendingBackupAction(nextAction)
    openBackupAccountSheet(nextAction === 'restore' ? 'signIn' : 'signUp')
    return false
  }

  function openBackupAccountSheet(mode = 'signIn') {
    setBackupAccountMode(mode)
    setBackupAccountEmail(backupConnection.email || businessProfile.companyEmail || '')
    setBackupAccountPassword('')
    setIsBackupAccountSheetOpen(true)
  }

  function closeBackupAccountSheet() {
    if (isBackupAccountSubmitting) {
      return
    }

    setIsBackupAccountSheetOpen(false)
  }

  async function submitBackupAccount() {
    setIsBackupAccountSubmitting(true)

    try {
      if (backupAccountMode === 'signUp') {
        const signUpResult = await signUpSupabaseBackupAccount(backupAccountEmail, backupAccountPassword)

        if (signUpResult.requiresEmailConfirmation) {
          setBackupAccountMode('signIn')
          setBackupAccountPassword('')
          Alert.alert(
            'Confirm your email',
            `Supabase sent a confirmation email to ${signUpResult.email}. Confirm it first, then sign in here to continue with backup or restore.`
          )
          return
        }
      } else {
        await signInSupabaseBackupAccount(backupAccountEmail, backupAccountPassword)
      }

      const connection = await refreshBackupConnection()
      const nextAction = pendingBackupAction

      setPendingBackupAction(null)
      setIsBackupAccountSheetOpen(false)
      setBackupAccountPassword('')

      if (nextAction === 'export') {
        await handleExportBackup()
        return
      }

      if (nextAction === 'restore') {
        await handleRestoreBackup()
        return
      }

      Alert.alert(
        'Backup account connected',
        `Supabase backup is ready for automatic bill, customer, and settings updates${connection.email ? ` on ${connection.email}` : ''}.`
      )
    } catch (error) {
      Alert.alert(
        backupAccountMode === 'signUp' ? 'Unable to create backup account' : 'Unable to sign in',
        error.message || 'Please try again.'
      )
    } finally {
      setIsBackupAccountSubmitting(false)
    }
  }

  function handleManageBackupAccount() {
    if (!isSupabaseBackupConfigured()) {
      Alert.alert(
        'Supabase backup not configured',
        'Add EXPO_PUBLIC_SUPABASE_URL and EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY to enable cloud backup and restore.'
      )
      return
    }

    if (!backupConnection.connected) {
      openBackupAccountSheet('signIn')
      return
    }

    Alert.alert(
      'Backup account',
      `Connected as ${backupConnection.email || 'this Supabase user'} on this device.`,
      [
        { text: 'Close', style: 'cancel' },
        {
          text: 'Use another account',
          onPress: () => {
            openBackupAccountSheet('signIn')
          },
        },
        {
          text: 'Sign out',
          style: 'destructive',
          onPress: () => {
            void disconnectBackupAccount()
          },
        },
      ]
    )
  }

  async function disconnectBackupAccount() {
    try {
      await signOutSupabaseBackupAccount()
      setPendingBackupAction(null)
      setBackupAccountPassword('')
      await refreshBackupConnection()
      Alert.alert('Backup account signed out', 'This device is no longer connected to your Supabase backup account.')
    } catch (error) {
      Alert.alert('Unable to sign out', error.message || 'Please try again.')
    }
  }

  async function handleDownloadBillFromList(bill) {
    setBusyAction('download')

    try {
      await persistBusinessSettings(false)
      await downloadPdf({
        ...bill,
        ...businessProfile,
      })
      Alert.alert('PDF ready', 'The invoice PDF was generated. Use the share sheet to save or send it.')
    } catch (error) {
      Alert.alert('Unable to generate PDF', error.message || 'Please try again.')
    } finally {
      setBusyAction(null)
    }
  }

  function confirmDeleteBill(bill) {
    Alert.alert('Delete bill', `Delete ${bill.invoiceNumber}?`, [
      { text: 'Cancel', style: 'cancel' },
      {
        text: 'Delete',
        style: 'destructive',
        onPress: async () => {
          await deleteBill(bill.id)
          await refreshRecords()
          scheduleAutomaticBackup()
          setScreen('launcher')
          setHomeTab('bills')
        },
      },
    ])
  }

  function confirmDeleteCustomer(customer) {
    const customerBillCount = bills.filter((bill) => bill.customerId === customer.id).length
    const message = customerBillCount
      ? `Delete ${customer.name}? ${customerBillCount} bill${customerBillCount > 1 ? 's' : ''} reference this customer. The invoices will keep their history but the customer link will be removed.`
      : `Delete ${customer.name}?`

    Alert.alert('Delete customer', message, [
      { text: 'Cancel', style: 'cancel' },
      {
        text: 'Delete',
        style: 'destructive',
        onPress: async () => {
          await deleteCustomer(customer.id)
          await refreshRecords()
          scheduleAutomaticBackup()
          setScreen('launcher')
          setHomeTab('customers')
          setIsCustomerSheetOpen(false)
          setCustomerSheetMode('view')
        },
      },
    ])
  }

  if (!isReady) {
    return (
      <AppShell>
        <CenteredMessage title="Preparing local billing desk" body="Opening the SQLite workspace and loading your records." />
        <BlockingLoaderOverlay visible={Boolean(blockingLoader)} loader={blockingLoader} lightMode={launcherIsLight} />
      </AppShell>
    )
  }

  if (loadError) {
    return (
      <AppShell>
        <CenteredMessage title="Database unavailable" body={loadError} />
      </AppShell>
    )
  }

  if (screen === 'edit' || screen === 'preview') {
    return (
      <AppShell
        backgroundColor={!launcherIsLight ? THEME.darkBackground : THEME.surface}
        statusBarStyle={!launcherIsLight ? 'light' : 'dark'}
      >
          <ScrollablePage isCompact={isCompact} resetScrollKey={screen}>
            <PageContent isCompact={isCompact} gapOverride={screen === 'edit' ? (isCompact ? 10 : 12) : undefined}>
              {screen === 'edit' ? (
                <ScreenHeader
                  
                  title="Bill Editor"
                  onBack={() => openLauncher('bills')}
                  isCompact={isCompact}
                  isWide={isWide}
                  lightMode={launcherIsLight}
                />
              ) : (
                <ScreenHeader
                 
                  title="Invoice Preview"
                  onBack={() => setScreen('edit')}
                  isCompact={isCompact}
                  isWide={isWide}
                  lightMode={launcherIsLight}
                />
              )}

              {screen === 'edit' ? (
                <InvoiceEditor
                  invoice={activeInvoice}
                  customers={customers}
                  summary={summary}
                  isCompact={isCompact}
                  isTablet={isTablet}
                  isWide={isWide}
                  isExistingBill={isExistingBill}
                  onFieldChange={updateField}
                  onItemChange={updateItem}
                  onAddItem={addItem}
                  onRemoveItem={confirmRemoveItem}
                  onApplyCustomer={applyCustomerToInvoice}
                  onPreview={handleOpenPreview}
                  lightMode={launcherIsLight}
                />
              ) : (
                <InvoicePreview
                  invoice={activeInvoice}
                  summary={summary}
                  cgstLabel={cgstLabel}
                  sgstLabel={sgstLabel}
                  showCompactPreview={showCompactPreview}
                  isCompact={isCompact}
                  isWide={isWide}
                  busyAction={busyAction}
                  onBack={() => setScreen('edit')}
                  onSave={confirmSaveInvoiceFromPreview}
                  onShare={handleSharePdf}
                  onDownload={handleDownloadPdf}
                  lightMode={launcherIsLight}
                />
              )}
            </PageContent>
          </ScrollablePage>
          </AppShell>
          )
          }
  return (
    <AppShell backgroundColor={launcherIsLight ? THEME.surface : THEME.darkBackground} statusBarStyle={launcherIsLight ? 'dark' : 'light'}>
      <GestureHandlerRootView style={{ flex: 1 }}>
        <ScrollView
          ref={launcherPagerRef}
          horizontal
          pagingEnabled
          directionalLockEnabled
          showsHorizontalScrollIndicator={false}
          bounces={false}
          scrollEventThrottle={16}
          keyboardShouldPersistTaps="handled"
          onMomentumScrollEnd={handleLauncherPagerMomentumEnd}
          contentOffset={{ x: Math.max(0, HOME_TAB_KEYS.indexOf(homeTab)) * width, y: 0 }}
          style={{ flex: 1 }}
        >
          <View style={launcherPageStyle(width)}>
            <ScrollablePage
              isCompact={isCompact}
              bottomPadding={showFloatingPrimaryAction ? (isCompact ? 204 : 218) : isCompact ? 128 : 140}
              onScroll={handleLauncherScroll}
            >
              <PageContent isCompact={isCompact}>
                <BillsHomeTab
                  bills={bills}
                  lightMode={launcherIsLight}
                  onCreateBill={() => createNewBill()}
                  onEditBill={openBillEditor}
                  onShareBill={handleShareBillFromList}
                  onShareBills={handleShareBillsFromList}
                  onDownloadBill={handleDownloadBillFromList}
                  onDeleteBill={confirmDeleteBill}
                />
              </PageContent>
            </ScrollablePage>
          </View>

          <View style={launcherPageStyle(width)}>
            <ScrollablePage
              isCompact={isCompact}
              bottomPadding={showFloatingPrimaryAction ? (isCompact ? 204 : 218) : isCompact ? 128 : 140}
              onScroll={handleLauncherScroll}
            >
              <PageContent isCompact={isCompact}>
                <CustomersHomeTab
                  customers={customers}
                  lightMode={launcherIsLight}
                  onCreateCustomer={createNewCustomer}
                  onEditCustomer={openCustomerEditor}
                  onCreateBillForCustomer={handleCreateBillFromCustomerSheet}
                  onDeleteCustomer={confirmDeleteCustomer}
                />
              </PageContent>
            </ScrollablePage>
          </View>

          <View style={launcherPageStyle(width)}>
            <ScrollablePage
              isCompact={isCompact}
              bottomPadding={showFloatingPrimaryAction ? (isCompact ? 204 : 218) : isCompact ? 128 : 140}
              onScroll={handleLauncherScroll}
            >
              <PageContent isCompact={isCompact}>
                <SettingsHomeTab
                  profile={businessProfile}
                  themeMode={themeMode}
                  lightMode={launcherIsLight}
                  onToggleTheme={toggleThemeMode}
                  isCompact={isCompact}
                  isTablet={isTablet}
                  backupBusyAction={dataTransferAction}
                  backupStatusTitle={
                    backupConnection.connected
                      ? 'Backup account connected'
                      : backupConnection.configured
                        ? 'Connect backup account'
                        : 'Supabase backup not configured'
                  }
                  backupStatusSubtitle={
                    backupConnection.connected
                      ? `Connected as ${backupConnection.email || 'your backup account'}`
                    : backupConnection.configured
                        ? 'Sign in or create a backup account to automatically upload bill, customer, and settings changes.'
                        : 'Add your Supabase URL and publishable key to enable cloud backup.'
                  }
                  onManageBackupAccount={handleManageBackupAccount}
                  onExportBackup={handleExportBackup}
                  onPickContact={pickBusinessContactFields}
                  onRestoreBackup={handleRestoreBackup}
                  onSaveProfile={(nextProfile, showSavedAlert = true) => persistBusinessProfileDraft(nextProfile, showSavedAlert)}
                />
              </PageContent>
            </ScrollablePage>
          </View>
        </ScrollView>

        <Animated.View
          pointerEvents={isBottomNavInteractive ? 'box-none' : 'none'}
          style={[
            bottomNavWrapStyle(isCompact, insets),
            {
              elevation: 40,
              opacity: bottomNavOpacity,
              transform: [{ translateY: bottomNavOffset }],
              zIndex: 40,
            },
          ]}
        >
          <View style={{ width: '100%', maxWidth: 1280, alignSelf: 'center' }}>
            {showFloatingPrimaryAction ? (
              <FloatingPrimaryAction
                label={homeTab === 'customers' ? 'Add Customer' : 'Add Bill'}
                onPress={homeTab === 'customers' ? createNewCustomer : () => createNewBill()}
                lightMode={launcherIsLight}
              />
            ) : null}
            <LedgerBottomNav activeTab={homeTab} onTabChange={handleHomeTabChange} lightMode={launcherIsLight} />
          </View>
        </Animated.View>

        <CustomerSheet
          visible={isCustomerSheetOpen}
          mode={customerSheetMode}
          customer={customerDraft || createCustomer()}
          isCompact={isCompact}
          isTablet={isTablet}
          isExistingCustomer={customers.some((customer) => customer.id === customerDraft?.id)}
          lightMode={launcherIsLight}
          onClose={closeCustomerSheet}
          onEdit={editCustomerInSheet}
          onFieldChange={updateCustomerDraftField}
          onSave={confirmPersistCustomerDraft}
          onDelete={() =>
            customers.some((customer) => customer.id === customerDraft?.id)
              ? confirmDeleteCustomer(customerDraft)
              : closeCustomerSheet()
          }
          onCreateBill={() => handleCreateBillFromCustomerSheet(customerDraft)}
          onPickFromContacts={importCustomerFromContacts}
        />

        <BackupAccountSheet
          visible={isBackupAccountSheetOpen}
          mode={backupAccountMode}
          email={backupAccountEmail}
          password={backupAccountPassword}
          submitting={isBackupAccountSubmitting}
          lightMode={launcherIsLight}
          isCompact={isCompact}
          isTablet={isTablet}
          onClose={closeBackupAccountSheet}
          onModeChange={setBackupAccountMode}
          onEmailChange={setBackupAccountEmail}
          onPasswordChange={setBackupAccountPassword}
          onSubmit={submitBackupAccount}
        />

        <BlockingLoaderOverlay visible={Boolean(blockingLoader)} loader={blockingLoader} lightMode={launcherIsLight} />
      </GestureHandlerRootView>
    </AppShell>
  )
}

function BlockingLoaderOverlay({ visible, loader, lightMode }) {
  if (!visible || !loader) {
    return null
  }

  return (
    <Modal transparent visible statusBarTranslucent animationType="fade" onRequestClose={() => {}}>
      <View style={blockingLoaderBackdropStyle}>
        <View style={blockingLoaderCardStyle(lightMode)}>
          <View style={blockingLoaderSpinnerWrapStyle(lightMode)}>
            <ActivityIndicator size="large" color={lightMode ? THEME.accentStrong : '#d7f6ea'} />
          </View>
          <View style={{ gap: 8 }}>
            <Text style={blockingLoaderTitleStyle(lightMode)}>{loader.title}</Text>
            <Text style={blockingLoaderBodyStyle(lightMode)}>{loader.body}</Text>
          </View>
          <View style={blockingLoaderPillStyle(lightMode)}>
            <Text style={blockingLoaderPillTextStyle(lightMode)}>Please keep this app open</Text>
          </View>
        </View>
      </View>
    </Modal>
  )
}

function BackupAccountSheet({
  visible,
  mode,
  email,
  password,
  submitting,
  lightMode,
  isCompact,
  isTablet,
  onClose,
  onModeChange,
  onEmailChange,
  onPasswordChange,
  onSubmit,
}) {
  const sheetTitle = mode === 'signUp' ? 'Create backup account' : 'Connect backup account'
  const sheetBody =
    mode === 'signUp'
      ? 'Create a small Supabase account for cloud backup. Use the same email and password on another device when you need to restore.'
      : 'Sign in with your Supabase backup account to upload a new backup or restore an existing one.'

  return (
    <Modal visible={visible} animationType="slide" transparent onRequestClose={onClose} statusBarTranslucent>
      <View style={backupSheetBackdropStyle}>
        <Pressable style={backupSheetScrimStyle} onPress={onClose} />
        <KeyboardAvoidingView
          behavior={Platform.OS === 'ios' ? 'padding' : undefined}
          style={backupSheetKeyboardAvoidingStyle}
        >
          <View
            style={[
              panelStyle,
              compactPanelStyle,
              backupSheetCardStyle(lightMode, isTablet),
              isCompact && backupSheetCompactCardStyle,
            ]}
          >
            <View style={backupSheetGrabberStyle(lightMode)} />
            <View style={backupSheetHeaderRowStyle}>
              <PanelHeader kicker="Cloud backup" title={sheetTitle} body={sheetBody} lightMode={lightMode} />
              <Pressable
                onPress={onClose}
                style={({ pressed }) => [
                  backupSheetCloseButtonStyle(lightMode),
                  pressed && { opacity: 0.86 },
                ]}
              >
                <Text style={backupSheetCloseButtonTextStyle(lightMode)}>Close</Text>
              </Pressable>
            </View>

            <ScrollView
              keyboardShouldPersistTaps="handled"
              showsVerticalScrollIndicator={false}
              contentContainerStyle={{ gap: 18 }}
            >
              <View style={backupModeToggleRowStyle}>
                <ActionButton
                  label="Sign in"
                  variant={mode === 'signIn' ? 'primary' : 'secondary'}
                  fullWidth
                  lightMode={lightMode}
                  disabled={submitting}
                  onPress={() => onModeChange('signIn')}
                />
                <ActionButton
                  label="Create account"
                  variant={mode === 'signUp' ? 'primary' : 'secondary'}
                  fullWidth
                  lightMode={lightMode}
                  disabled={submitting}
                  onPress={() => onModeChange('signUp')}
                />
              </View>

              <FieldGrid>
                <LabeledInput
                  label="Email"
                  value={email}
                  onChangeText={onEmailChange}
                  keyboardType="email-address"
                  autoCapitalize="none"
                  leftIcon="mail"
                  fullWidth
                  lightMode={lightMode}
                />
                <LabeledInput
                  label="Password"
                  value={password}
                  onChangeText={onPasswordChange}
                  autoCapitalize="none"
                  leftIcon="lock"
                  secureTextEntry
                  fullWidth
                  lightMode={lightMode}
                />
              </FieldGrid>

              <Text style={backupSheetHintTextStyle(lightMode)}>
                {mode === 'signUp'
                  ? 'Passwords need at least 6 characters. If email confirmation is enabled in Supabase, confirm first and then sign in here.'
                  : 'Use the same backup account you used when uploading the JSON backup.'}
              </Text>

              <ActionButton
                label={submitting ? (mode === 'signUp' ? 'Creating account...' : 'Connecting...') : mode === 'signUp' ? 'Create and continue' : 'Connect and continue'}
                iconName="cloud"
                fullWidth
                lightMode={lightMode}
                disabled={submitting}
                onPress={onSubmit}
              />
            </ScrollView>
          </View>
        </KeyboardAvoidingView>
      </View>
    </Modal>
  )
}

const backupSheetBackdropStyle = {
  flex: 1,
  backgroundColor: 'rgba(6, 24, 18, 0.42)',
}

const backupSheetScrimStyle = {
  flex: 1,
}

const backupSheetKeyboardAvoidingStyle = {
  justifyContent: 'flex-end',
}

function launcherPageStyle(width) {
  return {
    width,
    flex: 1,
  }
}

const blockingLoaderBackdropStyle = {
  flex: 1,
  justifyContent: 'center',
  alignItems: 'center',
  paddingHorizontal: 24,
  backgroundColor: 'rgba(6, 24, 18, 0.34)',
}

function blockingLoaderCardStyle(lightMode) {
  return {
    width: '100%',
    maxWidth: 380,
    gap: 16,
    paddingHorizontal: 22,
    paddingVertical: 24,
    borderRadius: 28,
    backgroundColor: lightMode ? 'rgba(255, 255, 255, 0.98)' : 'rgba(20, 20, 22, 0.98)',
    borderWidth: 1,
    borderColor: lightMode ? THEME.borderStrong : THEME.darkBorder,
    boxShadow: lightMode ? '0 20px 56px rgba(22, 74, 58, 0.18)' : '0 20px 56px rgba(0, 0, 0, 0.36)',
    borderCurve: 'continuous',
  }
}

function blockingLoaderSpinnerWrapStyle(lightMode) {
  return {
    width: 62,
    height: 62,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    backgroundColor: lightMode ? THEME.accentSoft : 'rgba(215, 246, 234, 0.08)',
  }
}

function blockingLoaderTitleStyle(lightMode) {
  return {
    fontFamily: 'Manrope_800ExtraBold',
    fontSize: 21,
    lineHeight: 27,
    textAlign: 'center',
    color: lightMode ? THEME.ink : THEME.darkText,
  }
}

function blockingLoaderBodyStyle(lightMode) {
  return {
    fontFamily: 'Manrope_500Medium',
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'center',
    color: lightMode ? THEME.muted : THEME.darkMuted,
  }
}

function blockingLoaderPillStyle(lightMode) {
  return {
    alignSelf: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: lightMode ? THEME.surfaceMuted : THEME.darkSurface,
    borderWidth: 1,
    borderColor: lightMode ? THEME.border : THEME.darkBorder,
  }
}

function blockingLoaderPillTextStyle(lightMode) {
  return {
    fontFamily: 'Manrope_700Bold',
    fontSize: 11,
    letterSpacing: 0.3,
    textTransform: 'uppercase',
    color: lightMode ? THEME.accentStrong : '#d7f6ea',
  }
}

function backupSheetCardStyle(lightMode, isTablet) {
  return {
    width: '100%',
    maxWidth: isTablet ? 720 : 640,
    alignSelf: 'center',
    gap: 18,
    padding: 22,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    backgroundColor: lightMode ? THEME.surface : THEME.darkSurfaceAlt,
    borderColor: lightMode ? THEME.border : THEME.darkBorder,
  }
}

const backupSheetCompactCardStyle = {
  paddingHorizontal: 16,
  paddingTop: 18,
}

function backupSheetGrabberStyle(lightMode) {
  return {
    width: 52,
    height: 5,
    borderRadius: 999,
    alignSelf: 'center',
    backgroundColor: lightMode ? THEME.accentSoftStrong : THEME.darkBorder,
  }
}

const backupSheetHeaderRowStyle = {
  flexDirection: 'row',
  justifyContent: 'space-between',
  gap: 16,
}

function backupSheetCloseButtonStyle(lightMode) {
  return {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    alignSelf: 'flex-start',
    backgroundColor: lightMode ? THEME.surfaceMuted : THEME.darkSurface,
    borderWidth: 1,
    borderColor: lightMode ? THEME.border : THEME.darkBorder,
  }
}

function backupSheetCloseButtonTextStyle(lightMode) {
  return {
    fontFamily: 'Manrope_600SemiBold',
    color: lightMode ? THEME.accentStrong : THEME.darkText,
    fontSize: 14,
  }
}

const backupModeToggleRowStyle = {
  flexDirection: 'row',
  gap: 12,
}

function backupSheetHintTextStyle(lightMode) {
  return {
    color: lightMode ? THEME.muted : THEME.darkMuted,
    fontSize: 13,
    lineHeight: 20,
  }
}
