import React, { useEffect, useRef, useState } from 'react'
import { Alert, Animated, Platform, Text, TextInput, View, useWindowDimensions } from 'react-native'
import * as Contacts from 'expo-contacts'
import { useFonts } from 'expo-font'
import {
  Manrope_400Regular,
  Manrope_500Medium,
  Manrope_600SemiBold,
  Manrope_700Bold,
  Manrope_800ExtraBold,
} from '@expo-google-fonts/manrope'

import { AppShell, CenteredMessage, PageContent, ScrollablePage } from './src/components/AppShell'
import { pickBackupDocument, shareBackupFile } from './src/backup'
import {
  BillsHomeTab,
  CustomersHomeTab,
  FloatingPrimaryAction,
  LedgerBottomNav,
  SettingsHomeTab,
  bottomNavWrapStyle,
} from './src/components/LauncherHome'
import CustomerSheet from './src/components/CustomerSheet'
import InvoiceEditor from './src/components/InvoiceEditor'
import InvoicePreview from './src/components/InvoicePreview'
import ScreenHeader from './src/components/ScreenHeader'
import { THEME } from './src/components/InvoiceComponents'
import { GestureHandlerRootView } from 'react-native-gesture-handler'
import { useSafeAreaInsets } from 'react-native-safe-area-context'
import { extractBusinessContactFields, extractCustomerFromContact } from './src/contactUtils'
import {
  createBill,
  createBusinessProfile,
  createCustomer,
  createItem,
  getDefaultState,
  mapCustomerToInvoiceFields,
} from './src/constants'
import {
  deleteBill,
  deleteCustomer,
  exportDatabaseBackup,
  getBusinessProfile,
  getThemeMode,
  initializeDatabase,
  listBills,
  listCustomers,
  replaceDatabaseWithBackup,
  saveBusinessProfile,
  saveBill,
  saveCustomer,
  saveThemeMode,
  summarizeBackupDocument,
} from './src/database'
import { downloadPdf, shareCombinedPdf, sharePdf } from './src/pdf'
import {
  getMinimumDueDate,
  calculateSummary,
  getGstLabels,
  getNextInvoiceNumber,
  hasPreviewableInvoiceItems,
  isDueDateAfterInvoiceDate,
  isAutoGeneratedInvoiceNumber,
  normalizeNumber,
} from './src/utils'

if (!globalThis.__riceTraderTypographyDefaultsApplied) {
  Text.defaultProps = Text.defaultProps || {}
  TextInput.defaultProps = TextInput.defaultProps || {}
  Text.defaultProps.style = [{ fontFamily: 'Manrope_500Medium' }, Text.defaultProps.style].filter(Boolean)
  TextInput.defaultProps.style = [{ fontFamily: 'Manrope_500Medium' }, TextInput.defaultProps.style].filter(Boolean)
  globalThis.__riceTraderTypographyDefaultsApplied = true
}

export default function App() {
  const insets = useSafeAreaInsets()
  const [fontsLoaded] = useFonts({
    Manrope_400Regular,
    Manrope_500Medium,
    Manrope_600SemiBold,
    Manrope_700Bold,
    Manrope_800ExtraBold,
  })
  const emptyInvoiceCustomerFields = {
    customerId: null,
    customerName: '',
    customerAddress: '',
    customerGstin: '',
    customerPhone: '',
    customerEmail: '',
    placeOfSupply: '',
  }
  const [customers, setCustomers] = useState([])
  const [bills, setBills] = useState([])
  const [invoice, setInvoice] = useState(null)
  const [customerDraft, setCustomerDraft] = useState(null)
  const [businessProfile, setBusinessProfile] = useState(() => createBusinessProfile())
  const [screen, setScreen] = useState('launcher')
  const [homeTab, setHomeTab] = useState('bills')
  const [busyAction, setBusyAction] = useState(null)
  const [isReady, setIsReady] = useState(false)
  const [loadError, setLoadError] = useState('')
  const [isCustomerSheetOpen, setIsCustomerSheetOpen] = useState(false)
  const [customerSheetMode, setCustomerSheetMode] = useState('view')
  const [themeMode, setThemeMode] = useState('light')
  const [dataTransferAction, setDataTransferAction] = useState(null)
  const { width } = useWindowDimensions()
  const bottomNavOffset = useRef(new Animated.Value(0)).current
  const bottomNavOpacity = useRef(new Animated.Value(1)).current
  const bottomNavVisible = useRef(true)
  const lastLauncherScrollY = useRef(0)
  const [isBottomNavInteractive, setIsBottomNavInteractive] = useState(true)
  const bottomNavAnimationUsesNativeDriver = Platform.OS !== 'android'

  const isCompact = width < 560
  const isTablet = width >= 720
  const isWide = width >= 960
  const showCompactPreview = width < 860
  const launcherIsLight = themeMode === 'light'
  const showFloatingPrimaryAction = screen === 'launcher' && (homeTab === 'bills' || homeTab === 'customers')
  const isExistingBill = invoice ? bills.some((bill) => bill.id === invoice.id) : false
  const activeInvoice = {
    ...(invoice || getDefaultState()),
    ...businessProfile,
  }
  const summary = calculateSummary(activeInvoice.items)
  const { cgstLabel, sgstLabel } = getGstLabels(activeInvoice.items)

  useEffect(() => {
    bootstrap()
  }, [])

  useEffect(() => {
    if (screen !== 'launcher') {
      revealBottomNav()
    }
  }, [screen])

  if (!fontsLoaded) {
    return null
  }

  function confirmAction({ title, message, confirmLabel, destructive = false, onConfirm }) {
    Alert.alert(title, message, [
      { text: 'Cancel', style: 'cancel' },
      {
        text: confirmLabel,
        style: destructive ? 'destructive' : 'default',
        onPress: () => {
          void onConfirm?.()
        },
      },
    ])
  }

  function hasCustomerDetails(customer) {
    return [
      customer?.name,
      customer?.address,
      customer?.gstin,
      customer?.phone,
      customer?.email,
      customer?.placeOfSupply,
      customer?.notes,
    ].some((value) => Boolean(String(value || '').trim()))
  }

  function createDraftBill(customer = null, overrides = {}, sourceBills = bills) {
    const nextBill = createBill({
      customerId: customer?.id || null,
      ...mapCustomerToInvoiceFields(customer),
      items: [],
      ...overrides,
    })

    return {
      ...nextBill,
      invoiceNumber: getNextInvoiceNumber(sourceBills, nextBill.invoiceDate, nextBill.id),
    }
  }

  async function bootstrap() {
    try {
      await initializeDatabase()
      await refreshRecords()
      setLoadError('')
      setIsReady(true)
    } catch (error) {
      setLoadError(error.message || 'Unable to open the local billing database.')
      setIsReady(true)
    }
  }

  async function refreshRecords(options = {}) {
    const [nextCustomers, nextBills, nextBusinessProfile, nextThemeMode] = await Promise.all([
      listCustomers(),
      listBills(),
      getBusinessProfile(),
      getThemeMode(),
    ])

    setCustomers(nextCustomers)
    setBills(nextBills)
    setBusinessProfile(nextBusinessProfile)
    setThemeMode(nextThemeMode)

    const nextInvoice =
      nextBills.find((bill) => bill.id === options.billId) ||
      nextBills.find((bill) => bill.id === invoice?.id) ||
      nextBills[0] ||
      createDraftBill(null, {}, nextBills)
    const nextCustomer =
      nextCustomers.find((customer) => customer.id === options.customerId) ||
      nextCustomers.find((customer) => customer.id === customerDraft?.id) ||
      nextCustomers[0] ||
      createCustomer()

    setInvoice(nextInvoice)
    setCustomerDraft(nextCustomer)
  }

  function updateField(field, value) {
    setInvoice((current) => {
      const baseInvoice = current || createDraftBill()
      const nextInvoice = {
        ...baseInvoice,
        [field]: value,
      }

      const isSavedBill = bills.some((bill) => bill.id === baseInvoice.id)
      if (field === 'invoiceDate' && !isSavedBill && isAutoGeneratedInvoiceNumber(baseInvoice.invoiceNumber)) {
        nextInvoice.invoiceNumber = getNextInvoiceNumber(bills, value, baseInvoice.id)
      }

      if (field === 'invoiceDate' && nextInvoice.dueDate && !isDueDateAfterInvoiceDate(value, nextInvoice.dueDate)) {
        nextInvoice.dueDate = getMinimumDueDate(value)
      }

      if (field === 'dueDate' && value && !isDueDateAfterInvoiceDate(nextInvoice.invoiceDate, value)) {
        nextInvoice.dueDate = getMinimumDueDate(nextInvoice.invoiceDate)
      }

      return nextInvoice
    })
  }

  function updateItem(itemId, field, value) {
    setInvoice((current) => ({
      ...(current || createDraftBill()),
      items: (current?.items || []).map((item) => (item.id === itemId ? { ...item, [field]: value } : item)),
    }))
  }

  function addItem() {
    const currentItems = invoice?.items || []
    const lastItem = currentItems[currentItems.length - 1]

    if (lastItem) {
      const missingFields = []

      if (!String(lastItem.description || '').trim()) {
        missingFields.push('description')
      }

      if (!String(lastItem.bagType || '').trim()) {
        missingFields.push('bag type')
      }

      if (normalizeNumber(lastItem.quantity) <= 0) {
        missingFields.push('quantity')
      }

      if (normalizeNumber(lastItem.rate) <= 0) {
        missingFields.push('rate')
      }

      if (missingFields.length > 0) {
        const missingLabel =
          missingFields.length === 1
            ? missingFields[0]
            : `${missingFields.slice(0, -1).join(', ')} and ${missingFields[missingFields.length - 1]}`

        Alert.alert(
          'Complete the current line item',
          `Fill the previous item's ${missingLabel} before adding a new line item.`
        )
        return
      }
    }

    setInvoice((current) => ({
      ...(current || createDraftBill()),
      items: [...(current?.items || []), createItem()],
    }))
  }

  function removeItem(itemId) {
    setInvoice((current) => {
      const nextItems = (current?.items || []).filter((item) => item.id !== itemId)

      return {
        ...(current || createDraftBill()),
        items: nextItems,
      }
    })
  }

  function updateCustomerDraftField(field, value) {
    setCustomerDraft((current) => ({
      ...(current || createCustomer()),
      [field]: value,
    }))
  }

  function confirmRemoveItem(itemId) {
    const item = (invoice?.items || []).find((entry) => entry.id === itemId)
    const itemLabel = String(item?.description || item?.bagType || 'this line item').trim()

    confirmAction({
      title: 'Remove item',
      message: `Remove ${itemLabel} from this invoice draft?`,
      confirmLabel: 'Remove',
      destructive: true,
      onConfirm: () => removeItem(itemId),
    })
  }

  function openLauncher(tab) {
    if (tab) {
      setHomeTab(tab)
    }
    revealBottomNav()
    setIsCustomerSheetOpen(false)
    setScreen('launcher')
  }

  function openBillEditor(bill) {
    revealBottomNav()
    setInvoice(bill)
    setScreen('edit')
    setHomeTab('bills')
  }

  function openCustomerEditor(customer) {
    revealBottomNav()
    setCustomerDraft(customer)
    setHomeTab('customers')
    setScreen('launcher')
    setCustomerSheetMode('view')
    setIsCustomerSheetOpen(true)
  }

  async function createNewBill(customer = null) {
    try {
      revealBottomNav()
      const nextBill = createDraftBill(customer)
      setInvoice(nextBill)
      setScreen('edit')
      setHomeTab('bills')
    } catch (error) {
      Alert.alert('Unable to create bill', error.message || 'Please try again.')
    }
  }

  async function persistBusinessProfileDraft(nextProfile, showSavedAlert) {
    try {
      const savedProfile = await saveBusinessProfile(nextProfile)
      setBusinessProfile(savedProfile)

      if (showSavedAlert) {
        Alert.alert('Settings saved', 'Business and bank setup were stored for all bills on this device.')
      }

      return savedProfile
    } catch (error) {
      Alert.alert('Unable to save settings', error.message || 'Please try again.')
      throw error
    }
  }

  async function persistBusinessSettings(showSavedAlert) {
    return persistBusinessProfileDraft(businessProfile, showSavedAlert)
  }

  async function pickSystemContact() {
    if (Platform.OS === 'web') {
      Alert.alert('Contacts unavailable', 'Contact import is available on Android and iPhone builds.')
      return null
    }

    try {
      const permission = await Contacts.requestPermissionsAsync()

      if (permission.status !== 'granted') {
        Alert.alert('Contacts permission needed', 'Allow contacts access to import a saved contact into the app.')
        return null
      }

      const selectedContact = await Contacts.presentContactPickerAsync()

      if (!selectedContact?.id) {
        return null
      }

      return (
        (await Contacts.getContactByIdAsync(selectedContact.id, [
          Contacts.Fields.Name,
          Contacts.Fields.FirstName,
          Contacts.Fields.LastName,
          Contacts.Fields.PhoneNumbers,
          Contacts.Fields.Emails,
          Contacts.Fields.Addresses,
        ])) || selectedContact
      )
    } catch (error) {
      Alert.alert('Unable to open contacts', error.message || 'Please try again.')
      return null
    }
  }

  async function importCustomerFromContacts() {
    const contact = await pickSystemContact()

    if (!contact) {
      return
    }

    const { phone } = extractCustomerFromContact(contact)

    if (!phone) {
      Alert.alert('No phone number found', 'The selected contact does not have a phone number to import.')
      return
    }

    setCustomerDraft((current) => ({
      ...(current || createCustomer()),
      phone,
    }))
  }

  async function pickBusinessContactFields() {
    const contact = await pickSystemContact()

    if (!contact) {
      return null
    }

    const nextFields = extractBusinessContactFields(contact)
    const { companyPhone, companyEmail } = nextFields

    if (!companyPhone && !companyEmail) {
      Alert.alert('No contact details found', 'The selected contact does not have a phone number or email to import.')
      return null
    }

    return Object.fromEntries(Object.entries(nextFields).filter(([, value]) => value))
  }

  function createNewCustomer() {
    revealBottomNav()
    setCustomerDraft(createCustomer())
    setHomeTab('customers')
    setScreen('launcher')
    setCustomerSheetMode('edit')
    setIsCustomerSheetOpen(true)
  }

  function hideBottomNav() {
    if (!bottomNavVisible.current) {
      return
    }

    bottomNavVisible.current = false
    setIsBottomNavInteractive(false)
    bottomNavOffset.stopAnimation()
    bottomNavOpacity.stopAnimation()
    Animated.parallel([
      Animated.timing(bottomNavOffset, {
        toValue: 120,
        duration: 220,
        useNativeDriver: bottomNavAnimationUsesNativeDriver,
      }),
      Animated.timing(bottomNavOpacity, {
        toValue: 0,
        duration: 180,
        useNativeDriver: bottomNavAnimationUsesNativeDriver,
      }),
    ]).start()
  }

  function revealBottomNav() {
    lastLauncherScrollY.current = 0

    if (bottomNavVisible.current) {
      setIsBottomNavInteractive(true)
      bottomNavOffset.stopAnimation()
      bottomNavOpacity.stopAnimation()
      bottomNavOffset.setValue(0)
      bottomNavOpacity.setValue(1)
      return
    }

    bottomNavVisible.current = true
    setIsBottomNavInteractive(true)
    bottomNavOffset.stopAnimation()
    bottomNavOpacity.stopAnimation()
    Animated.parallel([
      Animated.spring(bottomNavOffset, {
        toValue: 0,
        damping: 18,
        stiffness: 180,
        mass: 0.9,
        useNativeDriver: bottomNavAnimationUsesNativeDriver,
      }),
      Animated.timing(bottomNavOpacity, {
        toValue: 1,
        duration: 220,
        useNativeDriver: bottomNavAnimationUsesNativeDriver,
      }),
    ]).start()
  }

  function handleLauncherScroll(event) {
    const nextY = Math.max(0, event.nativeEvent.contentOffset.y)
    const delta = nextY - lastLauncherScrollY.current
    lastLauncherScrollY.current = nextY

    if (nextY <= 12) {
      revealBottomNav()
      return
    }

    if (delta > 8) {
      hideBottomNav()
      return
    }

    if (delta < -8) {
      revealBottomNav()
    }
  }

  function closeCustomerSheet() {
    setIsCustomerSheetOpen(false)
    setCustomerSheetMode('view')
  }

  function editCustomerInSheet() {
    setCustomerSheetMode('edit')
  }

  function handleCreateBillFromCustomerSheet(customer) {
    setIsCustomerSheetOpen(false)
    createNewBill(customer)
  }

  function handleHomeTabChange(tab) {
    revealBottomNav()
    setHomeTab(tab)
    setIsCustomerSheetOpen(false)
    setCustomerSheetMode('view')
  }

  async function toggleThemeMode() {
    const previousThemeMode = themeMode
    const nextThemeMode = previousThemeMode === 'light' ? 'dark' : 'light'

    setThemeMode(nextThemeMode)

    try {
      await saveThemeMode(nextThemeMode)
    } catch (error) {
      setThemeMode(previousThemeMode)
      Alert.alert('Unable to save theme', error.message || 'Please try again.')
    }
  }

  function applyCustomerToInvoice(customer) {
    setInvoice((current) => ({
      ...(current || createDraftBill()),
      ...(customer ? mapCustomerToInvoiceFields(customer) : emptyInvoiceCustomerFields),
      customerId: customer?.id || null,
    }))
  }

  async function persistInvoice(showSavedAlert) {
    const currentInvoice = activeInvoice

    try {
      const selectedCustomer = customers.find((customer) => customer.id === currentInvoice.customerId) || null
      const customerSnapshot = selectedCustomer
        ? mapCustomerToInvoiceFields(selectedCustomer)
        : emptyInvoiceCustomerFields
      const normalizedDueDate =
        currentInvoice.dueDate && !isDueDateAfterInvoiceDate(currentInvoice.invoiceDate, currentInvoice.dueDate)
          ? getMinimumDueDate(currentInvoice.invoiceDate)
          : currentInvoice.dueDate

      const savedBill = await saveBill({
        ...currentInvoice,
        dueDate: normalizedDueDate,
        customerId: selectedCustomer?.id || null,
        ...customerSnapshot,
      })

      await refreshRecords({
        billId: savedBill.id,
        customerId: selectedCustomer?.id || customerDraft?.id,
      })
      setInvoice(savedBill)

      if (showSavedAlert) {
        Alert.alert('Bill saved', 'The bill was stored on this device.')
      }

      return savedBill
    } catch (error) {
      Alert.alert('Unable to save bill', error.message || 'Please try again.')
      throw error
    }
  }

  async function persistCustomerDraft(showSavedAlert) {
    const currentCustomer = customerDraft || createCustomer()

    if (!hasCustomerDetails(currentCustomer)) {
      Alert.alert(
        'Customer details required',
        'Add at least one customer detail before saving this profile.'
      )
      return null
    }

    try {
      const savedCustomer = await saveCustomer(currentCustomer)
      await refreshRecords({ customerId: savedCustomer.id })
      setCustomerDraft(savedCustomer)

      if (invoice?.customerId === savedCustomer.id) {
        setInvoice((current) => ({
          ...(current || createDraftBill()),
          ...mapCustomerToInvoiceFields(savedCustomer),
          customerId: savedCustomer.id,
        }))
      }

      if (showSavedAlert) {
        Alert.alert('Customer saved', 'The customer profile was stored on this device.')
      }

      setIsCustomerSheetOpen(false)
      setCustomerSheetMode('view')
      setScreen('launcher')
      setHomeTab('customers')
      return savedCustomer
    } catch (error) {
      Alert.alert('Unable to save customer', error.message || 'Please try again.')
      throw error
    }
  }

  function confirmPersistCustomerDraft() {
    const currentCustomer = customerDraft || createCustomer()
    const isExistingCustomer = customers.some((customer) => customer.id === currentCustomer.id)
    const customerName = String(currentCustomer.name || 'this customer').trim()

    if (!hasCustomerDetails(currentCustomer)) {
      Alert.alert(
        'Customer details required',
        'Add at least one customer detail before creating a customer.'
      )
      return
    }

    confirmAction({
      title: isExistingCustomer ? 'Save customer changes' : 'Create customer',
      message: isExistingCustomer
        ? `Save the latest changes for ${customerName}?`
        : `Create ${customerName} in your local customer records?`,
      confirmLabel: isExistingCustomer ? 'Save' : 'Create',
      onConfirm: () => persistCustomerDraft(true),
    })
  }

  async function handleOpenPreview() {
    if (!hasPreviewableInvoiceItems(invoice?.items)) {
      Alert.alert(
        'Complete one item first',
        'Preview is available after at least one line item has a description, bag type, quantity, and rate.'
      )
      return
    }

    await persistBusinessSettings(false)
    setScreen('preview')
  }

  async function handleDownloadPdf() {
    setBusyAction('download')

    try {
      await persistBusinessSettings(false)
      const savedBill = await persistInvoice(false)
      await downloadPdf(savedBill)
      openLauncher('bills')
      Alert.alert('PDF ready', 'The invoice PDF was generated. Use the share sheet to save or send it.')
    } catch (error) {
      Alert.alert('Unable to generate PDF', error.message || 'Please try again.')
    } finally {
      setBusyAction(null)
    }
  }

  async function handleSharePdf() {
    setBusyAction('share')

    try {
      await persistBusinessSettings(false)
      const savedBill = await persistInvoice(false)
      await sharePdf(savedBill)
      openLauncher('bills')
    } catch (error) {
      Alert.alert('Unable to share PDF', error.message || 'Please try again.')
    } finally {
      setBusyAction(null)
    }
  }

  async function handleSaveFromPreview() {
    setBusyAction('save')

    try {
      await persistBusinessSettings(false)
      await persistInvoice(true)
      openLauncher('bills')
    } catch (error) {
      Alert.alert('Unable to save bill', error.message || 'Please try again.')
    } finally {
      setBusyAction(null)
    }
  }

  function confirmSaveInvoiceFromPreview() {
    const invoiceLabel = String(activeInvoice.invoiceNumber || 'this invoice').trim()

    confirmAction({
      title: 'Save invoice',
      message: `Save ${invoiceLabel} to your local billing records?`,
      confirmLabel: 'Save',
      onConfirm: () => handleSaveFromPreview(),
    })
  }

  async function handleShareBillFromList(bill) {
    setBusyAction('share')

    try {
      await persistBusinessSettings(false)
      await sharePdf({
        ...bill,
        ...businessProfile,
      })
    } catch (error) {
      Alert.alert('Unable to share PDF', error.message || 'Please try again.')
    } finally {
      setBusyAction(null)
    }
  }

  async function handleShareBillsFromList(selectedBills) {
    if (!selectedBills?.length) {
      return false
    }

    setBusyAction('share')

    try {
      await persistBusinessSettings(false)
      await shareCombinedPdf(
        selectedBills.map((bill) => ({
          ...bill,
          ...businessProfile,
        }))
      )
      return true
    } catch (error) {
      Alert.alert('Unable to share PDFs', error.message || 'Please try again.')
      return false
    } finally {
      setBusyAction(null)
    }
  }

  async function handleExportBackup() {
    setDataTransferAction('export')

    try {
      await persistBusinessSettings(false)
      const backup = await exportDatabaseBackup()
      const { fileName } = await shareBackupFile(backup)

      Alert.alert(
        'Backup ready',
        `A recovery file named ${fileName} is ready. Save it somewhere outside the app, like Files, Drive, or iCloud, so you can restore your data after reinstalling the app or moving phones.`
      )
    } catch (error) {
      Alert.alert('Unable to export backup', error.message || 'Please try again.')
    } finally {
      setDataTransferAction(null)
    }
  }

  async function performRestoreBackup(backupText, fileName) {
    setDataTransferAction('restore')

    try {
      const restoreSummary = await replaceDatabaseWithBackup(backupText)
      await refreshRecords()
      openLauncher('settings')

      Alert.alert(
        'Backup restored',
        `${fileName} restored ${restoreSummary.customers} customers, ${restoreSummary.bills} bills, and ${restoreSummary.settings} settings on this device.`
      )
    } catch (error) {
      Alert.alert('Unable to restore backup', error.message || 'Please try again.')
    } finally {
      setDataTransferAction(null)
    }
  }

  async function handleRestoreBackup() {
    try {
      const selectedBackup = await pickBackupDocument()

      if (!selectedBackup) {
        return
      }

      const restoreSummary = summarizeBackupDocument(selectedBackup.contents)

      Alert.alert(
        'Restore backup',
        `Replace the current local data on this device with ${selectedBackup.fileName}?\n\nCustomers: ${restoreSummary.customers}\nBills: ${restoreSummary.bills}\nSettings: ${restoreSummary.settings}\n\nThis overwrites the app's current local records on this device.`,
        [
          { text: 'Cancel', style: 'cancel' },
          {
            text: 'Restore',
            style: 'destructive',
            onPress: () => {
              void performRestoreBackup(selectedBackup.contents, selectedBackup.fileName)
            },
          },
        ]
      )
    } catch (error) {
      Alert.alert('Unable to read backup', error.message || 'Please choose a valid backup file and try again.')
    }
  }

  async function handleDownloadBillFromList(bill) {
    setBusyAction('download')

    try {
      await persistBusinessSettings(false)
      await downloadPdf({
        ...bill,
        ...businessProfile,
      })
      Alert.alert('PDF ready', 'The invoice PDF was generated. Use the share sheet to save or send it.')
    } catch (error) {
      Alert.alert('Unable to generate PDF', error.message || 'Please try again.')
    } finally {
      setBusyAction(null)
    }
  }

  function confirmDeleteBill(bill) {
    Alert.alert('Delete bill', `Delete ${bill.invoiceNumber}?`, [
      { text: 'Cancel', style: 'cancel' },
      {
        text: 'Delete',
        style: 'destructive',
        onPress: async () => {
          await deleteBill(bill.id)
          await refreshRecords()
          setScreen('launcher')
          setHomeTab('bills')
        },
      },
    ])
  }

  function confirmDeleteCustomer(customer) {
    const customerBillCount = bills.filter((bill) => bill.customerId === customer.id).length
    const message = customerBillCount
      ? `Delete ${customer.name}? ${customerBillCount} bill${customerBillCount > 1 ? 's' : ''} reference this customer. The invoices will keep their history but the customer link will be removed.`
      : `Delete ${customer.name}?`

    Alert.alert('Delete customer', message, [
      { text: 'Cancel', style: 'cancel' },
      {
        text: 'Delete',
        style: 'destructive',
        onPress: async () => {
          await deleteCustomer(customer.id)
          await refreshRecords()
          setScreen('launcher')
          setHomeTab('customers')
          setIsCustomerSheetOpen(false)
          setCustomerSheetMode('view')
        },
      },
    ])
  }

  if (!isReady) {
    return (
      <AppShell>
        <CenteredMessage title="Preparing local billing desk" body="Opening the SQLite workspace and loading your records." />
      </AppShell>
    )
  }

  if (loadError) {
    return (
      <AppShell>
        <CenteredMessage title="Database unavailable" body={loadError} />
      </AppShell>
    )
  }

  if (screen === 'edit' || screen === 'preview') {
    return (
      <AppShell
        backgroundColor={!launcherIsLight ? THEME.darkBackground : THEME.surface}
        statusBarStyle={!launcherIsLight ? 'light' : 'dark'}
      >
          <ScrollablePage isCompact={isCompact}>
            <PageContent isCompact={isCompact} gapOverride={screen === 'edit' ? (isCompact ? 10 : 12) : undefined}>
              {screen === 'edit' ? (
                <ScreenHeader
                  
                  title="Bill Editor"
                  onBack={() => openLauncher('bills')}
                  isCompact={isCompact}
                  isWide={isWide}
                  lightMode={launcherIsLight}
                />
              ) : (
                <ScreenHeader
                 
                  title="Invoice Preview"
                  onBack={() => setScreen('edit')}
                  isCompact={isCompact}
                  isWide={isWide}
                  lightMode={launcherIsLight}
                />
              )}

              {screen === 'edit' ? (
                <InvoiceEditor
                  invoice={activeInvoice}
                  customers={customers}
                  summary={summary}
                  isCompact={isCompact}
                  isTablet={isTablet}
                  isWide={isWide}
                  isExistingBill={isExistingBill}
                  onFieldChange={updateField}
                  onItemChange={updateItem}
                  onAddItem={addItem}
                  onRemoveItem={confirmRemoveItem}
                  onApplyCustomer={applyCustomerToInvoice}
                  onPreview={handleOpenPreview}
                  lightMode={launcherIsLight}
                />
              ) : (
                <InvoicePreview
                  invoice={activeInvoice}
                  summary={summary}
                  cgstLabel={cgstLabel}
                  sgstLabel={sgstLabel}
                  showCompactPreview={showCompactPreview}
                  isCompact={isCompact}
                  isWide={isWide}
                  busyAction={busyAction}
                  onBack={() => setScreen('edit')}
                  onSave={confirmSaveInvoiceFromPreview}
                  onShare={handleSharePdf}
                  onDownload={handleDownloadPdf}
                  lightMode={launcherIsLight}
                />
              )}
            </PageContent>
          </ScrollablePage>
          </AppShell>
          )
          }
  return (
    <AppShell backgroundColor={launcherIsLight ? THEME.surface : THEME.darkBackground} statusBarStyle={launcherIsLight ? 'dark' : 'light'}>
      <GestureHandlerRootView style={{ flex: 1 }}>
        <ScrollablePage
          isCompact={isCompact}
          bottomPadding={showFloatingPrimaryAction ? (isCompact ? 204 : 218) : isCompact ? 128 : 140}
          onScroll={handleLauncherScroll}
        >
          <PageContent isCompact={isCompact}>
            {homeTab === 'bills' ? (
              <BillsHomeTab
                bills={bills}
                lightMode={launcherIsLight}
                onCreateBill={() => createNewBill()}
                onEditBill={openBillEditor}
                onShareBill={handleShareBillFromList}
                onShareBills={handleShareBillsFromList}
                onDownloadBill={handleDownloadBillFromList}
                onDeleteBill={confirmDeleteBill}
              />
            ) : homeTab === 'customers' ? (
              <CustomersHomeTab
                customers={customers}
                lightMode={launcherIsLight}
                onCreateCustomer={createNewCustomer}
                onEditCustomer={openCustomerEditor}
                onCreateBillForCustomer={handleCreateBillFromCustomerSheet}
                onDeleteCustomer={confirmDeleteCustomer}
              />
            ) : (
              <SettingsHomeTab
                profile={businessProfile}
                themeMode={themeMode}
                lightMode={launcherIsLight}
                onToggleTheme={toggleThemeMode}
                isCompact={isCompact}
                isTablet={isTablet}
                backupBusyAction={dataTransferAction}
                onExportBackup={handleExportBackup}
                onPickContact={pickBusinessContactFields}
                onRestoreBackup={handleRestoreBackup}
                onSaveProfile={(nextProfile, showSavedAlert = true) => persistBusinessProfileDraft(nextProfile, showSavedAlert)}
              />
            )}
          </PageContent>
        </ScrollablePage>

        <Animated.View
          pointerEvents={isBottomNavInteractive ? 'box-none' : 'none'}
          style={[
            bottomNavWrapStyle(isCompact, insets),
            {
              elevation: 40,
              opacity: bottomNavOpacity,
              transform: [{ translateY: bottomNavOffset }],
              zIndex: 40,
            },
          ]}
        >
          <View style={{ width: '100%', maxWidth: 1280, alignSelf: 'center' }}>
            {showFloatingPrimaryAction ? (
              <FloatingPrimaryAction
                label={homeTab === 'customers' ? 'Add Customer' : 'Add Bill'}
                onPress={homeTab === 'customers' ? createNewCustomer : () => createNewBill()}
                lightMode={launcherIsLight}
              />
            ) : null}
            <LedgerBottomNav activeTab={homeTab} onTabChange={handleHomeTabChange} lightMode={launcherIsLight} />
          </View>
        </Animated.View>

        <CustomerSheet
          visible={isCustomerSheetOpen}
          mode={customerSheetMode}
          customer={customerDraft || createCustomer()}
          isCompact={isCompact}
          isTablet={isTablet}
          isExistingCustomer={customers.some((customer) => customer.id === customerDraft?.id)}
          lightMode={launcherIsLight}
          onClose={closeCustomerSheet}
          onEdit={editCustomerInSheet}
          onFieldChange={updateCustomerDraftField}
          onSave={confirmPersistCustomerDraft}
          onDelete={() =>
            customers.some((customer) => customer.id === customerDraft?.id)
              ? confirmDeleteCustomer(customerDraft)
              : closeCustomerSheet()
          }
          onCreateBill={() => handleCreateBillFromCustomerSheet(customerDraft)}
          onPickFromContacts={importCustomerFromContacts}
        />
      </GestureHandlerRootView>
    </AppShell>
  )
}
