export function formatCurrency(value) {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 2,
  }).format(normalizeNumber(value))
}

export function formatPlainCurrency(value) {
  return new Intl.NumberFormat('en-IN', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(normalizeNumber(value))
}

export function formatNumber(value) {
  return new Intl.NumberFormat('en-IN', {
    minimumFractionDigits: Number.isInteger(normalizeNumber(value)) ? 0 : 2,
    maximumFractionDigits: 2,
  }).format(normalizeNumber(value))
}

export function formatReadableDate(value) {
  if (!value) {
    return '-'
  }

  const date = new Date(`${value}T00:00:00`)

  if (Number.isNaN(date.getTime())) {
    return value
  }

  return new Intl.DateTimeFormat('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  }).format(date)
}

export function formatDateInput(date) {
  const year = date.getFullYear()
  const month = String(date.getMonth() + 1).padStart(2, '0')
  const day = String(date.getDate()).padStart(2, '0')
  return `${year}-${month}-${day}`
}

export function formatInvoiceNumberDate(value) {
  const date = parseInvoiceDate(value)

  return `${String(date.getFullYear()).slice(-2)}${String(date.getMonth() + 1).padStart(2, '0')}${String(
    date.getDate()
  ).padStart(2, '0')}`
}

export function isAutoGeneratedInvoiceNumber(value) {
  return /^INV-\d{6}-\d{3}$/.test(String(value || '').trim())
}

export function getNextInvoiceNumber(bills, invoiceDate, currentBillId = null) {
  const dateToken = formatInvoiceNumberDate(invoiceDate)
  const invoicePattern = new RegExp(`^INV-${dateToken}-(\\d{3})$`)
  const maxSequence = (Array.isArray(bills) ? bills : []).reduce((currentMax, bill) => {
    if (!bill || bill.id === currentBillId) {
      return currentMax
    }

    const match = String(bill.invoiceNumber || '').match(invoicePattern)
    if (!match) {
      return currentMax
    }

    return Math.max(currentMax, Number(match[1]))
  }, 0)

  return `INV-${dateToken}-${String(maxSequence + 1).padStart(3, '0')}`
}

export function addDays(date, days) {
  const next = new Date(date)
  next.setDate(next.getDate() + days)
  return next
}

export function isDueDateAfterInvoiceDate(invoiceDate, dueDate) {
  if (!invoiceDate || !dueDate) {
    return true
  }

  return parseInvoiceDate(dueDate).getTime() > parseInvoiceDate(invoiceDate).getTime()
}

export function getMinimumDueDate(invoiceDate) {
  return formatDateInput(addDays(parseInvoiceDate(invoiceDate), 1))
}

export const INDIA_PHONE_PREFIX = '+91'

export function getIndianPhoneDigits(value) {
  const rawValue = String(value || '').trim()
  let digits = rawValue.replace(/\D/g, '')

  if (!digits) {
    return ''
  }

  const hasExplicitPrefix =
    rawValue.startsWith(INDIA_PHONE_PREFIX) ||
    rawValue.startsWith('91 ') ||
    rawValue.startsWith('91-') ||
    rawValue.startsWith('91.')

  if ((hasExplicitPrefix || digits.length > 10) && digits.startsWith('91')) {
    digits = digits.slice(2)
  }

  if (digits.length > 10) {
    digits = digits.slice(-10)
  }

  return digits.slice(0, 10)
}

export function normalizeIndianPhoneNumber(value) {
  const digits = getIndianPhoneDigits(value)
  return digits ? `${INDIA_PHONE_PREFIX} ${digits}` : ''
}

function parseInvoiceDate(value) {
  if (value instanceof Date && !Number.isNaN(value.getTime())) {
    return value
  }

  if (typeof value === 'string') {
    const match = value.match(/^(\d{4})-(\d{2})-(\d{2})$/)

    if (match) {
      const [, year, month, day] = match
      const parsed = new Date(Number(year), Number(month) - 1, Number(day))

      if (!Number.isNaN(parsed.getTime())) {
        return parsed
      }
    }

    const parsed = new Date(value)
    if (!Number.isNaN(parsed.getTime())) {
      return parsed
    }
  }

  return new Date()
}

export function normalizeNumber(value) {
  const normalized =
    typeof value === 'string' ? Number(value.replace(/,/g, '').trim()) : Number(value)

  return Number.isFinite(normalized) ? normalized : 0
}

export function escapeHtml(value) {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
}

export function formatMultilineText(value) {
  return escapeHtml(value).replaceAll('\n', '<br />')
}

export function calculateItem(item) {
  const quantity = normalizeNumber(item.quantity)
  const rate = normalizeNumber(item.rate)
  const gstRate = normalizeNumber(item.gstRate)
  const taxable = quantity * rate
  const gstAmount = (taxable * gstRate) / 100
  const lineTotal = taxable + gstAmount

  return {
    taxable,
    gstAmount,
    lineTotal,
  }
}

export function calculateSummary(items) {
  return items.reduce(
    (summary, item) => {
      const totals = calculateItem(item)
      summary.quantityTotal += normalizeNumber(item.quantity)
      summary.taxableTotal += totals.taxable
      summary.gstTotal += totals.gstAmount
      summary.cgstTotal += totals.gstAmount / 2
      summary.sgstTotal += totals.gstAmount / 2
      summary.grandTotal += totals.lineTotal
      return summary
    },
    { quantityTotal: 0, taxableTotal: 0, gstTotal: 0, cgstTotal: 0, sgstTotal: 0, grandTotal: 0 }
  )
}

export function isInvoiceItemReady(item) {
  const hasDescription = Boolean(item?.description?.trim())
  const hasBagType = Boolean(item?.bagType?.trim())
  const hasQuantity = normalizeNumber(item?.quantity) > 0
  const hasRate = normalizeNumber(item?.rate) > 0

  return hasDescription && hasBagType && hasQuantity && hasRate
}

export function hasPreviewableInvoiceItems(items) {
  return Array.isArray(items) && items.some((item) => isInvoiceItemReady(item))
}

export function getGstLabels(items) {
  const uniqueGstRates = [...new Set(items.map((item) => normalizeNumber(item.gstRate)))]
  const splitRate = uniqueGstRates.length === 1 ? uniqueGstRates[0] / 2 : null

  return {
    cgstLabel: splitRate === null ? 'CGST' : `CGST @ ${formatNumber(splitRate)}%`,
    sgstLabel: splitRate === null ? 'SGST' : `SGST @ ${formatNumber(splitRate)}%`,
  }
}

export function convertAmountToWords(amount) {
  const whole = Math.floor(normalizeNumber(amount))
  const decimals = Math.round((normalizeNumber(amount) - whole) * 100)
  const rupees = numberToIndianWords(whole)
  const paise = decimals ? `${numberToIndianWords(decimals)} Paise` : 'Zero Paise'
  return `${rupees} Rupees and ${paise} Only`
}

export function numberToIndianWords(value) {
  if (value === 0) {
    return 'Zero'
  }

  const ones = [
    '',
    'One',
    'Two',
    'Three',
    'Four',
    'Five',
    'Six',
    'Seven',
    'Eight',
    'Nine',
    'Ten',
    'Eleven',
    'Twelve',
    'Thirteen',
    'Fourteen',
    'Fifteen',
    'Sixteen',
    'Seventeen',
    'Eighteen',
    'Nineteen',
  ]
  const tens = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety']

  const toWordsBelowThousand = (num) => {
    const hundred = Math.floor(num / 100)
    const remainder = num % 100
    const parts = []

    if (hundred) {
      parts.push(`${ones[hundred]} Hundred`)
    }

    if (remainder) {
      if (remainder < 20) {
        parts.push(ones[remainder])
      } else {
        const ten = Math.floor(remainder / 10)
        const one = remainder % 10
        parts.push([tens[ten], ones[one]].filter(Boolean).join(' '))
      }
    }

    return parts.join(' ')
  }

  const crore = Math.floor(value / 10000000)
  const lakh = Math.floor((value % 10000000) / 100000)
  const thousand = Math.floor((value % 100000) / 1000)
  const hundredRemainder = value % 1000
  const words = []

  if (crore) {
    words.push(`${numberToIndianWords(crore)} Crore`)
  }

  if (lakh) {
    words.push(`${toWordsBelowThousand(lakh)} Lakh`)
  }

  if (thousand) {
    words.push(`${toWordsBelowThousand(thousand)} Thousand`)
  }

  if (hundredRemainder) {
    words.push(toWordsBelowThousand(hundredRemainder))
  }

  return words.join(' ').trim()
}

export function makeId() {
  if (globalThis.crypto?.randomUUID) {
    return globalThis.crypto.randomUUID()
  }

  return `item-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`
}
